plugins {
    id 'com.android.application'
}

android {
    namespace 'com.zgqinc.bmi'
    compileSdk 35

    defaultConfig {
        applicationId "com.zgqinc.bmi"
        minSdk 16
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
        }
    }

    buildFeatures {
        buildConfig false
        aidl false
        renderScript false
        viewBinding false
    }

    packagingOptions {
        exclude 'META-INF/*'
    }

    lintOptions {
        abortOnError false
    }
}